### PR TITLE
Add iOS9 new non-standard shrink-to-fit directive

### PR DESCRIPTION
**Pull request by patrickhlauke**
as per https://www.bram.us/2015/10/06/ios9-mobilesafari-viewport-problem/ and many others...

### CODE REVIEW

**Comment by iandevlin** [comment]
Cool thanks, although there are other files that need to have it added and explained, so I will merge this later and then update the other files accordingly.

**Comment by patrickhlauke** [comment]
ah sorry fella, missed out the other ones stupidly. i can change these and force-push an update

**Comment by patrickhlauke** [comment]
force-pushed, with amendments to the missing files

**Comment by iandevlin** [comment]
Cool, thanks!

**Comment by MahmoudMaher0** [comment]
I don't understand , who are you ?

2016-04-25 17:00 GMT+02:00 Ian Devlin <notifications@github.com>:

**Pull request merged**
